#!/usr/bin/env python
from xml.dom.minidom import parse, getDOMImplementation
import os, sys

if len(sys.argv) != 3:
    print 'Usage:',sys.argv[0],'directory','tag'
    sys.exit(1)

impl = getDOMImplementation()

doc = impl.createDocument(None, sys.argv[2] + 's', None)
top = doc.documentElement

files = os.listdir(sys.argv[1])
for file in files:
    if file.endswith('.xml'):
        dom = parse(sys.argv[1] + '/' + file)
        els = dom.getElementsByTagName(sys.argv[2])
        for el in els:
                top.appendChild(el.cloneNode(True))
        dom.unlink()

print '<?xml version="1.0"?>\n\n'
print '<!-- this file is autogenerated! -->\n\n'
print top.toprettyxml()
