<div class="sidebar">
    <div class="sidebar-section">
        <a href="/" class="navigation">News</a><br/>
        <a href="/about.shtml" class="navigation">About</a><br/>
    </div>
    <div class="sidebar-section">
        <a href="http://flickr.com/photos/56529747@N00/sets/72157600306325564/" class="navigation">Gallery</a><br/>
        <a href="http://flickr.com/photos/56529747@N00/sets/72157600305970586/" class="navigation">Screenshots</a><br/>
        <a href="http://flapjack.navi.cx/releases/fyre/" class="navigation">Download</a><br/>
    </div>
</div>
