<div class="sidebar">
    <div class="sidebar-section">
        <a href="/" class="navigation">News</a><br/>
        <a href="/about.shtml" class="navigation">About</a><br/>
    </div>
    <div class="sidebar-section">
        <a href="http://zero.navi.cx/gallery/v/software/fyre/" class="navigation">Gallery</a><br/>
        <a href="http://zero.navi.cx/gallery/v/software/fyre-screenshots/" class="navigation">Screenshots</a><br/>
        <a href="http://flapjack.navi.cx/releases/fyre/" class="navigation">Download</a><br/>
    </div>
</div>
