CLASSES=\
	keyinfo.class\
	key.class\
	question.class

update: $(CLASSES)

keyinfo.class: keyinfo.java
	javac keyinfo.java

key.class: key.java
	javac key.java

question.class: question.java
	javac question.java

clean:
	rm -Rf *.class *~
