CLASSES=\
	element.class\
	reader.class\
	updater.class

update: $(CLASSES)

element.class: element.java
	javac element.java

reader.class: reader.java
	javac reader.java

updater.class: updater.java
	javac updater.java

clean:
	rm -Rf *.class *~
