#!/usr/bin/env python

Import ('env')
env.Append (CCFLAGS = '-g')

# Build the server
screamersd_sources = [
	'screamersd.cpp',
	'textUtils.cpp',
	'tinyxmlparser.cpp',
	'tinyxmlerror.cpp',
	'tinyxml.cpp',
	'world.cpp',
	'worldParser.cpp',
]
env.Program ('screamersd', screamersd_sources)

# Build the client
screamers_sources = [
	'application.cpp',
	'frameListener.cpp',
	'screamers.cpp',
]
env.Program ('screamers', screamers_sources)
