#!/usr/bin/env python

Import ('env')
env.Append (CCFLAGS = '-g')

# Build the server
screamersd_sources = [
	'screamersd.cpp',
]
env.Program ('screamersd', screamersd_sources)

# Build the client
screamers_sources = [
	'application.cpp',
	'frame-listener.cpp',
	'screamers.cpp',
]
env.Program ('screamers', screamers_sources)
