#!/usr/bin/env python

tnlenv = Environment (CPPPATH = 'libtomcrypt', LIBS = 'tomcrypt', LIBPATH = 'libtomcrypt')
Export ('tnlenv')

tnl_sources = [
	'assert.cpp',
	'asymmetricKey.cpp',
	'bitStream.cpp',
	'byteBuffer.cpp',
	'certificate.cpp',
	'clientPuzzle.cpp',
	'connectionStringTable.cpp',
	'dataChunker.cpp',
	'eventConnection.cpp',
	'ghostConnection.cpp',
	'huffmanStringProcessor.cpp',
	'journal.cpp',
	'log.cpp',
	'netBase.cpp',
	'netConnection.cpp',
	'netInterface.cpp',
	'netObject.cpp',
	'netStringTable.cpp',
	'platform.cpp',
	'random.cpp',
	'rpc.cpp',
	'symmetricCipher.cpp',
	'thread.cpp',
	'tnlMethodDispatch.cpp',
	'udp.cpp',
	'vector.cpp',
]

tnlenv.StaticLibrary ('tnl', tnl_sources)
