#!/usr/bin/env python

''' sheetViewer

A small program for viewing and creating character sheets.  Does not build new
layouts for character sheets, can only use existing layouts and create new data
files using those layouts.

  Copyright (C) 2003, W. Evan Sheehan <evan@navi.cx>
'''

import sys, gtk, gtk.glade
from GTKsheet import GTKsheet
from Character import Character

def init(filename=None):
  ''' Initialize the window and stuff using glade. '''
  # Create the window from the XML file.
  global tree
  tree = gtk.glade.XML('sheetviewer.glade')
  tree.OpenSheetDialog = tree.get_widget('OpenSheetDialog')
  tree.SaveSheetDialog = tree.get_widget('SaveSheetDialog')
  tree.ViewPort = tree.get_widget('SheetViewPort')
  
  # Create the window with a sheet already loaded.
  if filename:
    OpenSheet(filename)

  for func in globals().iterkeys():
    if func.startswith('on_'):
      tree.signal_connect(func, globals()[func])

def OpenSheet(filename):
  ''' Open a new character sheet. '''
  if hasattr(tree, 'sheet'):
    tree.ViewPort.remove(tree.sheet.root)

  if hasattr(tree, 'characterData'):
    tree.characterData.setNodeAttr('/character', {'layout':filename})
  else:
    tree.characterData = Character(filename)

  tree.sheet = GTKsheet(tree.characterData)
  tree.ViewPort.add(tree.sheet.root)
  tree.sheet.root.edit.set_active(gtk.TRUE)
  tree.sheet.root.editable()
  tree.sheet.root.show()

##### Signal handlers #####
def on_window_destroy(widget=None, data=None):
  gtk.main_quit()

def on_quit_activate(widget=None, data=None):
  gtk.main_quit()

def on_New_activate(widget, data=None):
  tree.characterData = Character()
  tree.characterData.makeNewDoc()
  tree.OpenSheetDialog.set_filename('layout/')
  tree.OpenSheetDialog.show()

def on_Open_activate(widget, data=None):
  del tree.characterData
  tree.OpenSheetDialog.set_filename('data/')
  tree.OpenSheetDialog.show()

def on_Save_activate(widget, data=None):
  tree.SaveSheetDialog.set_filename('data/')
  tree.SaveSheetDialog.show()

def on_cancel_open_button_clicked(widget, data=None):
  tree.OpenSheetDialog.hide()
  tree.OpenSheetDialog.set_filename('..')

def on_ok_open_button_clicked(widget, data=None):
  OpenSheet(tree.OpenSheetDialog.get_filename())
  tree.OpenSheetDialog.hide()
  tree.OpenSheetDialog.set_filename('..')

def on_cancel_save_button_clicked(widget, data=None):
  tree.SaveSheetDialog.hide()

def on_ok_save_button_clicked(widget, data=None):
  tree.characterData.filename = tree.SaveSheetDialog.get_filename()
  tree.sheet.root.applyChanges()
  tree.characterData.writeOut()
  tree.SaveSheetDialog.hide()

if __name__ == '__main__':
  if len(sys.argv) > 1:
    init(sys.argv[1])
  else:
    init()
  gtk.main()
