#!/usr/bin/env python

''' sheetViewer

A small program for viewing and creating character sheets.  Does not build new
layouts for character sheets, can only use existing layouts and create new data
files using those layouts.

  Copyright 2003, W. Evan Sheehan <evan@navi.cx>
'''

import sys, gtk, gtk.glade
from GTKsheet import GTKsheet
from Character import Character

def init():
  ''' Initialize the window and stuff using glade. '''
  global tree
  tree = gtk.glade.XML('sheetviewer.glade')

  for func in globals().iterkeys():
    if func.startswith('on_'):
      tree.signal_connect(func, globals()[func])

def on_window_destroy(widget=None, data=None):
  gtk.main_quit()

def on_quit_activate(widget=None, data=None):
  gtk.main_quit()

def on_new_activate(widget, data=None):
  print 'Not implemented.'

def on_open_activate(widget, data=None):
  print 'Not implemented.'

def on_cancel_button_clicked(widget, data=None):
  print widget
  print data
if __name__ == '__main__':
  init()
  gtk.main()
