<?xml version="1.0"?>
<gstreamer xmlns:gst="http://gstreamer.net/gst-core/1.0/">
  <gst:element>
    <gst:name>pipeline</gst:name>
    <gst:type>pipeline</gst:type>
    <gst:version>0.4.0.1</gst:version>
    <gst:param>
      <gst:name>name</gst:name>
      <gst:value>pipeline</gst:value>
    </gst:param>
    <gst:children>
      <gst:element>
        <gst:name>disk_source</gst:name>
        <gst:type>filesrc</gst:type>
        <gst:version>0.4.0.1</gst:version>
        <gst:param>
          <gst:name>name</gst:name>
          <gst:value>disk_source</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>offset</gst:name>
          <gst:value>0</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>location</gst:name>
          <gst:value>/home/musicus/muzak/Debussy_Claude/clair_de_lune.mp3</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>filesize</gst:name>
          <gst:value>0</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>fd</gst:name>
          <gst:value>0</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>blocksize</gst:name>
          <gst:value>4096</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>mmapsize</gst:name>
          <gst:value>4194304</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>touch</gst:name>
          <gst:value>TRUE</gst:value>
        </gst:param>
        <gst:pad>
          <gst:name>src</gst:name>
          <gst:peer>decoder.sink</gst:peer>
        </gst:pad>
      </gst:element>
      <gst:element>
        <gst:name>decoder</gst:name>
        <gst:type>mad</gst:type>
        <gst:version>0.4.0.1</gst:version>
        <gst:param>
          <gst:name>name</gst:name>
          <gst:value>decoder</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>layer</gst:name>
          <gst:value>0</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>mode</gst:name>
          <gst:value>-1</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>emphasis</gst:name>
          <gst:value>-1</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>bitrate</gst:name>
          <gst:value>0</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>samplerate</gst:name>
          <gst:value>0</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>channels</gst:name>
          <gst:value>0</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>average-bitrate</gst:name>
          <gst:value>0</gst:value>
        </gst:param>
        <gst:pad>
          <gst:name>sink</gst:name>
          <gst:peer>disk_source.src</gst:peer>
        </gst:pad>
        <gst:pad>
          <gst:name>src</gst:name>
          <gst:peer>splitter.sink</gst:peer>
        </gst:pad>
      </gst:element>
      <gst:element>
        <gst:name>splitter</gst:name>
        <gst:type>stereosplit</gst:type>
        <gst:version>0.4.0.1</gst:version>
        <gst:param>
          <gst:name>name</gst:name>
          <gst:value>splitter</gst:value>
        </gst:param>
        <gst:pad>
          <gst:name>sink</gst:name>
          <gst:peer>decoder.src</gst:peer>
        </gst:pad>
        <gst:pad>
          <gst:name>src1</gst:name>
          <gst:peer>net-sink.sink</gst:peer>
        </gst:pad>
        <gst:pad>
          <gst:name>src2</gst:name>
          <gst:peer>local-sink.sink</gst:peer>
        </gst:pad>
      </gst:element>
      <gst:element>
        <gst:name>local-sink</gst:name>
        <gst:type>osssink</gst:type>
        <gst:version>0.4.0.1</gst:version>
        <gst:param>
          <gst:name>name</gst:name>
          <gst:value>local-sink</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>device</gst:name>
          <gst:value>/dev/dsp</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>mute</gst:name>
          <gst:value>FALSE</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>format</gst:name>
          <gst:value>16</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>channels</gst:name>
          <gst:value>2</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>frequency</gst:name>
          <gst:value>48000</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>fragment</gst:name>
          <gst:value>6</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>buffer-size</gst:name>
          <gst:value>4096</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>sync</gst:name>
          <gst:value>TRUE</gst:value>
        </gst:param>
        <gst:pad>
          <gst:name>sink</gst:name>
          <gst:peer>splitter.src2</gst:peer>
        </gst:pad>
      </gst:element>
      <gst:element>
        <gst:name>net-sink</gst:name>
        <gst:type>esdsink</gst:type>
        <gst:version>0.4.0.1</gst:version>
        <gst:param>
          <gst:name>name</gst:name>
          <gst:value>net-sink</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>mute</gst:name>
          <gst:value>FALSE</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>depth</gst:name>
          <gst:value>16</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>channels</gst:name>
          <gst:value>2</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>frequency</gst:name>
          <gst:value>44100</gst:value>
        </gst:param>
        <gst:param>
          <gst:name>host</gst:name>
          <gst:value>128.138.2.123</gst:value>
        </gst:param>
        <gst:pad>
          <gst:name>sink</gst:name>
          <gst:peer>splitter.src1</gst:peer>
        </gst:pad>
      </gst:element>
    </gst:children>
  </gst:element>
</gstreamer>
