#!/usr/bin/env python

import sys, gtk
from GTKsheet import GTKsheet
from Character import Character

character = Character()
character.readCharacter(sys.argv[1])
sheet = GTKsheet(character)

window = gtk.Window(gtk.WINDOW_TOPLEVEL)
window.connect('delete_event', lambda w, d: gtk.main_quit())
window.add(sheet.root)
sheet.root.show()
window.show()
gtk.main()
