CLASSES=\
	keyinfo.class\
	key.class\
	element.class

update: $(CLASSES)

keyinfo.class: keyinfo.java
	javac keyinfo.java

key.class: key.java
	javac key.java

element.class: element.java
	javac element.java

clean:
	rm -Rf *.class *~
