#!/usr/bin/env python
'''	trough
	Simple command-line interface to trough.
	It really is, believe me.  Uh-huh.
	'''

from types import *
import sys

# This really needs to go somewhere better.  But for the meantime... it won't.
version = '0.0.0'

# Set up and run command line parser
#
import CommandLine
parser = CommandLine.OptionParser (version=version)
parser.add_option('-a','--add',dest='add',action="store_true",
		help="recursively add path(s) to the playlist")
parser.add_option('-b','--break',dest='breakup',action="store_true",
		help="break up grouped files already in tree")
parser.add_option('-p','--playlist',dest="playlist",type="string",
		help="path to playlist file",default="~/.trough-playlist")
parser.add_option('-r','--remove',dest='remove',action="store_true",
		help="recursively remove path(s) to the playlist")
#parser.add_option('-i','--info',dest='info',action="store_true",
#		help="retrieve information on current playlist")
parser.add_option('-v','--verbose',dest="verbose",action="store_true",
		help="give verbose output")
(options,arguments) = parser.parse_args()

# Deal with command line options & arguments
#
import Select
from PlayList import PlayList

playlist = PlayList(options.playlist)
if options.add and options.remove:
	parser.error("can't simultaneously add and remove")
if options.add:
	print 'adding ',arguments
	playlist.getPieces().addPaths(arguments)
	playlist.dump()
	sys.exit(0)
if options.remove:
	print 'removing ',arguments
	playlist.getPieces().removePaths(arguments)
	playlist.dump()
	sys.exit(0)
if options.breakup:
	print 'breaking ',arguments
	playlist.getPieces().breakPieces(arguments)
	playlist.dump()
	sys.exit(0)

# At some point, this may be replaced by code that actually plays something
#
p = playlist.getPieces()
                                                                                
for x in Select.Select(p):
	print x.getPath()
