#!/usr/bin/env python

Import ('env')

common_sources = [
	'version.cpp',
]

# Build the server
screamersd_sources = [
	'screamersd.cpp',
]
env.Program ('screamersd', common_sources + screamersd_sources)

# Build the client
cenv = env.Copy (LIBS = ['GL'])
screamers_sources = [
	'screamers.cpp',
]
cenv.Program ('screamers',  common_sources + screamers_sources)
