#!/usr/bin/env python

Import ('env')

# Build the server
screamersd_sources = [
	'screamersd.cpp',
]
env.Program ('screamersd', screamersd_sources)

# Build the client
cenv = env.Copy (LIBS = ['GL'])
screamers_sources = [
	'screamers.cpp',
]
cenv.Program ('screamers', screamers_sources)
