#!/usr/bin/env python

Import ('env')
env.ParseConfig ('pkg-config --cflags --libs OGRE')

# Build the server
screamersd_sources = [
	'screamersd.cpp',
]
env.Program ('screamersd', screamersd_sources)

# Build the client
screamers_sources = [
	'screamers.cpp',
]
env.Program ('screamers', screamers_sources)
