#!/usr/bin/env python

import CommandLine
import Select
import sys
from types import *

cmdl = CommandLine.CommandLine()

p = cmdl.getPieces()
p.addPaths (sys.argv[1:])
                                                                                
for x in Select.Select(p):
	print x.getPath()
