#
# rcpod build script for SCons (http://www.scons.org)
#


########### Directories and source files

libSrc = [
    'device.c'
    ]
testProgs = [
    'blinkytest'
    ]
libHeader = 'include/rcpod.h'
prefix = '/usr'


########### Build targets

# Add our local include directory to the C preprocessor path
env = Environment()
env['CPPPATH'] = 'include'

# Building librcpod
librcpod = env.SharedLibrary('rcpod',
                             ["src/%s" % file for file in libSrc],
                             LIBS=['usb'])

# Building the test programs
for testName in testProgs:
    env.Program(testName, 'test/%s.c' % testName, LIBS=['rcpod'])

# Installing librcpod
libDir = "%s/lib" % prefix
includeDir = "%s/include" % prefix
env.Alias('install', [libDir, includeDir])
env.Install(dir=libDir, source=librcpod)
env.Install(dir=includeDir, source=libHeader)


### The End ###
