all:	sonate-cello.pdf sonate-piano.pdf

sonate-cello.pdf:	prologue-cello.ly serenade-finale-cello.ly text.ly sonate-cello.ly
	lilypond sonate-cello.ly

sonate-piano.pdf:	prologue-cello.ly prologue-piano.ly serenade-finale-cello.ly serenade-finale-piano.ly text.ly sonate-piano.ly
	lilypond sonate-piano.ly
