DOCNAME = report

PROTOTYPE_DIR = ../../low-fi_prototype
SVG_FIGURES = $(PROTOTYPE_DIR)/new_lesson_dialog.svg	\
	      $(PROTOTYPE_DIR)/button_mouseover.svg	\
	      $(PROTOTYPE_DIR)/add_field_dialog.svg	\
	      $(PROTOTYPE_DIR)/linked_lessons.svg	\
	      $(PROTOTYPE_DIR)/add_to_box.svg		\
	      $(PROTOTYPE_DIR)/new_box_dialog.svg	\
	      $(PROTOTYPE_DIR)/teaching_box.svg	
STATIC_FIGURES =
GENERATED_FIGURES =

LIB_DIR = ../lib
include $(LIB_DIR)/Rules.make
