# Yes, this needs to be here twice. Not sure why...
sudo /usr/bin/nvtv -t -r 640,480 -s normal -S NTSC
sudo /usr/bin/nvtv -t -r 640,480 -s normal -S NTSC

# The X server seems to be sucking up way more CPU than
# it should, this makes other processes like the media
# player and VFD thread much more responsive
sudo /usr/bin/snice +10 X

export DISPLAY=:0
xhost +

cd ~/freevo
while true; do ./freevo; sleep 1; done
