sudo nvtv -t -S NTSC -r 800,600 -s Large
sudo nvtv -t -S NTSC -r 800,600 -s Large

export DISPLAY=:0
xhost +

xset dpms force off
xset dpms 0 0 0
xset -dpms

irexec -d ~/wasabi/lircrc

cd ~/freevo-1.5.2
while true; do ./freevo; sleep 1; done
