#!/bin/bash

echo "**** building amc module ****";
cd amc;
make install;
cd ..;

echo "**** building motion module ****";
cd motion;
make install;
cd ..;

echo "**** building graph_node module ****";
cd graph_node;
make;
cd ..;

echo "**** generating graph_interp/conversion.h ****";
cd graph_interp;
./build_convert.pl > conversion.h;
cd ..;
echo;

echo "**** building amc_graph module ****";
cd amc_graph;
make install;
cd ..;

echo "**** building graph_interp module ****";
cd graph_interp;
make install;
cd ..;

echo "**** installing combine tool ****";
cd combine;
make install;
cd ..;

echo "**** installing rootstrip tool ****";
cd rootstrip;
make install;
cd ..;
