#!/usr/bin/env python
from distutils import sysconfig
import sys

# screamers3d library information - this is probably broken on non-posix OSes

files = [
	'src\screamers3d.cpp',
	]

env = Environment ()
env.Append (CCFLAGS = '-g')

# include paths
env.Append (CPPPATH = './inc')
env.Append (CPPPATH = './src')

# libraries
env.Append (LIBS = 'pthread')
env.Append (LIBS = 'util')
env.Append (LIBS = 'gl')


env.Program ('screamers3d', source = files)
