#!/usr/bin/env python
from distutils import sysconfig
import sys

SConscript(['src/SConscript'])

env = Environment ()
env.Append (CCFLAGS = '-g')

# include paths
env.Append (CPPPATH = './inc')
env.Append (CPPPATH = './src')

# libraries
env.Append (LIBS = 'pthread')
env.Append (LIBS = 'util')
env.Append (LIBS = 'gl')


env.Program ('screamers', source = client_files)
